import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'admin',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'user',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Puma',
        logo: '/images/logo1.png',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
  ],
  products: [
    {
      name: 'Product 01',
      category: 'Category01',
      image: '/images/p4.jpg',
      price: 150,
      countInStock: 8,
      brand: 'brand01',
      rating: 4.5,
      numReviews: 10,
      description: 'description text',
    },
    {
      name: 'Product 02',
      category: 'Category01',
      image: '/images/p3.jpg',
      price: 150,
      countInStock: 8,
      brand: 'brand01',
      rating: 4.5,
      numReviews: 9,
      description: 'description text',
    },
    {
      name: 'Product 03',
      category: 'Category01',
      image: '/images/p2.jpg',
      price: 850,
      countInStock: 8,
      brand: 'brand01',
      rating: 4.5,
      numReviews: 5,
      description: 'description text',
    },
    {
      name: 'Product 04',
      category: 'Category01',
      image: '/images/p2.jpg',
      price: 150,
      countInStock: 8,
      brand: 'brand01',
      rating: 3,
      numReviews: 8,
      description: 'description text',
    },
    {
      name: 'Product 05',
      category: 'Category01',
      image: '/images/p2.jpg',
      price: 110,
      countInStock: 8,
      brand: 'brand01',
      rating: 4.2,
      numReviews: 8,
      description: 'description text',
    },
    {
      name: 'Product 06',
      category: 'Category01',
      image: '/images/p4.jpg',
      price: 190,
      countInStock: 8,
      brand: 'brand01',
      rating: 4.0,
      numReviews: 6,
      description: 'description text',
    },
    {
      name: 'Product 07',
      category: 'Category01',
      image: '/images/p3.jpg',
      price: 3.5,
      countInStock: 8,
      brand: 'brand01',
      rating: 4.5,
      numReviews: 10,
      description: 'description text',
    },
    {
      name: 'Product 08',
      category: 'Category01',
      image: '/images/p2.jpg',
      price: 160,
      countInStock: 0,
      brand: 'brand01',
      rating: 1.5,
      numReviews: 10,
      description: 'description text',
    },
  ],
};
export default data;
