export const PATIENT_CREATE_REQUEST = 'PATIENT_CREATE_REQUEST';
export const PATIENT_CREATE_SUCCESS = 'PATIENT_CREATE_SUCCESS';
export const PATIENT_CREATE_FAIL = 'PATIENT_CREATE_FAIL';
export const PATIENT_CREATE_RESET = 'PATIENT_CREATE_RESET';
