export const PRESCRIPTION_CREATE_REQUEST = 'PRESCRIPTION_CREATE_REQUEST';
export const PRESCRIPTION_CREATE_SUCCESS = 'PRESCRIPTION_CREATE_SUCCESS';
export const PRESCRIPTION_CREATE_FAIL = 'PRESCRIPTION_CREATE_FAIL';
export const PRESCRIPTION_CREATE_RESET = 'PRESCRIPTION_CREATE_RESET';

export const PRESCRIPTION_LIST_REQUEST = 'PRESCRIPTION_LIST_REQUEST';
export const PRESCRIPTION_LIST_SUCCESS = 'PRESCRIPTION_LIST_SUCCESS';
export const PRESCRIPTION_LIST_FAIL = 'PRESCRIPTION_LIST_FAIL';
export const PRESCRIPTION_LIST_RESET = 'PRESCRIPTION_LIST_RESET';

export const PRESCRIPTION_ORDER_DELIVER_REQUEST =
  'PRESCRIPTION_ORDER_DELIVER_REQUEST';
export const PRESCRIPTION_ORDER_DELIVER_SUCCESS =
  'PRESCRIPTION_ORDER_DELIVER_SUCCESS';
export const PRESCRIPTION_ORDER_DELIVER_FAIL =
  'PRESCRIPTION_ORDER_DELIVER_FAIL';
export const PRESCRIPTION_ORDER_DELIVER_RESET =
  'PRESCRIPTION_ORDER_DELIVER_RESET';

export const PRESCRIPTION_ORDER_DISPATCH_REQUEST =
  'PRESCRIPTION_ORDER_DISPATCH_REQUEST';
export const PRESCRIPTION_ORDER_DISPATCH_SUCCESS =
  'PRESCRIPTION_ORDER_DISPATCH_SUCCESS';
export const PRESCRIPTION_ORDER_DISPATCH_FAIL =
  'PRESCRIPTION_ORDER_DISPATCH_FAIL';
export const PRESCRIPTION_ORDER_DISPATCH_RESET =
  'PRESCRIPTION_ORDER_DISPATCH_RESET';
