export const PRESCRIPTION_CREATE_REQUEST = 'PRESCRIPTION_CREATE_REQUEST';
export const PRESCRIPTION_CREATE_SUCCESS = 'PRESCRIPTION_CREATE_SUCCESS';
export const PRESCRIPTION_CREATE_FAIL = 'PRESCRIPTION_CREATE_FAIL';
export const PRESCRIPTION_CREATE_RESET = 'PRESCRIPTION_CREATE_RESET';

export const PRESCRIPTION_LIST_REQUEST = 'PRESCRIPTION_LIST_REQUEST';
export const PRESCRIPTION_LIST_SUCCESS = 'PRESCRIPTION_LIST_SUCCESS';
export const PRESCRIPTION_LIST_FAIL = 'PRESCRIPTION_LIST_FAIL';
export const PRESCRIPTION_LIST_RESET = 'PRESCRIPTION_LIST_RESET';
