const data = {
  products: [
    {
      _id: '1',
      name: 'Product 01',
      category: 'Category01',
      image: '/images/p1.jpg',
      price: 150,
      brand: 'brand01',
      rating: 4.5,
      numReviews: 10,
      description: 'description text',
    },
    {
      _id: '2',
      name: 'Product 02',
      category: 'Category01',
      image: '/images/p1.jpg',
      price: 150,
      brand: 'brand01',
      rating: 4.5,
      numReviews: 9,
      description: 'description text',
    },
    {
      _id: '3',
      name: 'Product 03',
      category: 'Category01',
      image: '/images/p1.jpg',
      price: 850,
      brand: 'brand01',
      rating: 4.5,
      numReviews: 5,
      description: 'description text',
    },
    {
      _id: '4',
      name: 'Product 04',
      category: 'Category01',
      image: '/images/p1.jpg',
      price: 150,
      brand: 'brand01',
      rating: 3,
      numReviews: 8,
      description: 'description text',
    },
    {
      _id: '5',
      name: 'Product 05',
      category: 'Category01',
      image: '/images/p1.jpg',
      price: 110,
      brand: 'brand01',
      rating: 4.2,
      numReviews: 8,
      description: 'description text',
    },
    {
      _id: '6',
      name: 'Product 06',
      category: 'Category01',
      image: '/images/p1.jpg',
      price: 190,
      brand: 'brand01',
      rating: 4.0,
      numReviews: 6,
      description: 'description text',
    },
    {
      _id: '7',
      name: 'Product 07',
      category: 'Category01',
      image: '/images/p1.jpg',
      price: 3.5,
      brand: 'brand01',
      rating: 4.5,
      numReviews: 10,
      description: 'description text',
    },
    {
      _id: '8',
      name: 'Product 08',
      category: 'Category01',
      image: '/images/p1.jpg',
      price: 160,
      brand: 'brand01',
      rating: 1.5,
      numReviews: 10,
      description: 'description text',
    },
  ],
};
export default data;
